# Generated by Django 4.1.5 on 2024-12-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_designationinfo_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
