# Generated by Django 4.1.5 on 2024-12-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_employeeinfo_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='is_deleted',
        ),
    ]
