# Generated by Django 4.1.5 on 2024-12-17 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0017_alter_employeeinfo_info_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='info_of',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
