# Generated by Django 5.1.3 on 2024-12-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_receptonist_user_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permanentaddress',
            old_name='permanent_upzila',
            new_name='permanent_brgy',
        ),
        migrations.RenameField(
            model_name='permanentaddress',
            old_name='present_division',
            new_name='permanent_city',
        ),
        migrations.RenameField(
            model_name='permanentaddress',
            old_name='permanent_village',
            new_name='permanent_country',
        ),
        migrations.RenameField(
            model_name='permanentaddress',
            old_name='permanent_district',
            new_name='permanent_province',
        ),
        migrations.RenameField(
            model_name='permanentaddress',
            old_name='permanent_post',
            new_name='permanent_street',
        ),
        migrations.RenameField(
            model_name='presentaddress',
            old_name='present_upzila',
            new_name='present_brgy',
        ),
        migrations.RenameField(
            model_name='presentaddress',
            old_name='present_division',
            new_name='present_city',
        ),
        migrations.RenameField(
            model_name='presentaddress',
            old_name='present_village',
            new_name='present_country',
        ),
        migrations.RenameField(
            model_name='presentaddress',
            old_name='present_district',
            new_name='present_province',
        ),
        migrations.RenameField(
            model_name='presentaddress',
            old_name='present_post',
            new_name='present_street',
        ),
    ]
